- name: csv_test_1
  hosts: localhost
  tasks:
  - name: Path to CSV, delimeter $, register to object users, localhost
    community.general.read_csv:
      path: jinja2_hostname.csv
      delimiter: $
    register: jinja_csr
    delegate_to: localhost

#  - name: Creating Loop
#    ansible.builtin.debug:
#      msg: "Testing {{ item.hostname }}"
#    loop: "{{ users.list }}"

  - name: Jinja Template
    template:
      src: jinja_hostname.j2
      dest: "/var/lib/awx/projects/_66__jinja_templating/config/{{ item.hostname }}.txt"
    loop: "{{ jinja_csr.list }}"
